config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.id } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :currencies, only: %i[index show]
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'currencies#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency.rb
# frozen_string_literal: true

class Currency < ApplicationRecord
  has_many :price_movements

  def price_usd
    price_movements.last.price_usd
  end
end

app/models/price_movement.rb
# frozen_string_literal: true

class PriceMovement < ApplicationRecord
  belongs_to :currency
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :send_welcome_email
  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, notice: 'Please Login!'
    end
  end
end

app/controllers/currencies_controller.rb
# frozen_string_literal: true

class CurrenciesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_currency, only: %i[show]

  # GET /currencies or /currencies.json
  def index
    @currencies = Currency.all
  end

  # GET /currencies/1 or /currencies/1.json
  def show
    @price_movements = @currency.price_movements.order(timestamp: :desc).limit(24)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_currency
    @currency = Currency.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/currencies_helper.rb
# frozen_string_literal: true

module CurrenciesHelper
  def diff_class(diff)
    diff.to_f.positive? ? 'text-success' : 'text-danger'
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/currencies/index.html.erb
<%= javascript_include_tag "currencies/currency_index", "data-turbo-track": "reload", defer: true %>
<h2>Daily Coin Info</h2>
<br>

<table id="currency_list" class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Market Cap</th>
      <th>1hr</th>
      <th>24hr</th>
      <th>7day</th>
    </tr>
  </thead>
  <tbody>
    <% @currencies.each do |currency| %>
      <tr class="cursor-pointer" data-link="<%= currency_path(currency) %>">
        <td><%= currency.name %></td>
        <td class="text-end"><%= number_to_currency currency.price_usd %></td>
        <td class="text-end"><%= number_to_currency currency.market_cap_usd %></td>
        <td class="text-end <%= diff_class(currency.change_percent_1hr) %>">
          <%= number_to_percentage currency.change_percent_1hr, precision: 2 %>
        </td>
        <td class="text-end <%= diff_class(currency.change_percent_24hr) %>">
          <%= number_to_percentage currency.change_percent_24hr, precision: 2 %>
        </td>
        <td class="text-end <%= diff_class(currency.change_percent_7d) %>">
          <%= number_to_percentage currency.change_percent_7d, precision: 2 %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/currencies/show.html.erb
<%= javascript_include_tag "currencies/currency_show", "data-turbo-track": "reload", defer: true %>

<h2><%= @currency.name %></h2>
<br/>
<div id="container" style="width:100%; height:400px;"></div>

<h2>Daily Coin Info</h2>
<br>

<table id="currency_price_list" class="table table-hover table-bordered">
  <thead>
  <tr>
    <th>Currency</th>
    <th>Timestamp</th>
    <th>Price</th>
  </tr>
  </thead>

  <tbody>
  <% @price_movements.each do |price_movement| %>
    <tr>
      <td><%= @currency.name %></td>
      <td class="text-end"><%= price_movement.timestamp.strftime("%m/%d/%Y %l:%M %p") %></td>
      <td class="text-end"><%= number_to_currency price_movement.price_usd %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<script>
    window.prices = <%= @price_movements.to_json.html_safe %>;
</script>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div> Welcome <%= current_user.email %> </div>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= button_to "Sign up", new_user_registration_path, method: :get %>
  <%= button_to "Sign in", new_user_session_path, method: :get %>
<% end %>

<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoCap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar bg-primary bg-opacity-10">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          Crypto Cap
        </a>
        <% if user_signed_in? %>
          <div class="d-flex">
            <div class="me-2"> <%= current_user.name.presence || current_user.email %> </div>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
          </div>
        <% end %>
      </div>
    </nav>
    <div class="container-lg pt-4">
      <div style="float: right">
        <p class="notice text-info"><%= notice %></p>
        <p class="alert text-danger"><%= alert %></p>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>